import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Symbiosis",
  description: "Generated by create next app",
  icons: "./icon.ico",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <section>{children}</section>;
}
