import type { Metadata } from "next";
import localFont from "next/font/local";
import WagmiRainbowKitProvider from "../components/providers/WagmiRainbowKitProvider";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import { ToastContainer } from "react-toastify";
// import SideBar from "./components/Sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const satoshi = localFont({
  src: "../public/fonts/satoshi/Satoshi-Variable.woff",
  variable: "--font-satoshi",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Sei App",
  description: "Generated by create next app",
  icons: "../icon.ico",
  keywords: "Sei app, sei bridge",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <WagmiRainbowKitProvider>
        <ToastContainer
          autoClose={2000}
          hideProgressBar={true}
          theme="colored"
        />
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${satoshi.variable} antialiased`}
        >
          {/* Global styling and providers (e.g., font styles) */}
          {children}
        </body>
      </WagmiRainbowKitProvider>
    </html>
  );
}
